/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.ImageIcon;

/**
 *
 * @author Vinicius Santiago
 */
public class JanelaInicial extends javax.swing.JFrame {

    private static JanelaInicial janelaInicio;
    private static final ImageIcon image = new ImageIcon (System.getProperty("user.dir")+"/src/Model/Imagens/Concessionaria.jpg");

    public static JanelaInicial getJanelaInicio() {
        if (janelaInicio == null) {
            janelaInicio = new JanelaInicial();
            image.setImage(image.getImage().getScaledInstance(janelaInicio.lbConc.getWidth(), janelaInicio.lbConc.getHeight(), 1));
            janelaInicio.lbConc.setIcon (image);
        }
        return janelaInicio;
    }
    /**
     * Creates new form CadastroPneu
     */
    private JanelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        jButtonPneus = new javax.swing.JButton();
        jButtonAcessorios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbConc = new javax.swing.JLabel();
        jButtonCarros1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setMinimumSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(null);

        btSair.setBackground(new java.awt.Color(204, 204, 204));
        btSair.setForeground(new java.awt.Color(0, 0, 0));
        btSair.setText("Sign Out");
        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btSairMouseClicked(evt);
            }
        });
        getContentPane().add(btSair);
        btSair.setBounds(320, 10, 130, 40);

        jButtonPneus.setBackground(new java.awt.Color(0, 0, 0));
        jButtonPneus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPneus.setText("Pneus");
        jButtonPneus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPneusMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonPneus);
        jButtonPneus.setBounds(10, 360, 90, 40);

        jButtonAcessorios.setBackground(new java.awt.Color(0, 0, 0));
        jButtonAcessorios.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAcessorios.setText("Acessorios");
        jButtonAcessorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAcessoriosMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonAcessorios);
        jButtonAcessorios.setBounds(340, 360, 110, 40);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Vini's Car");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 20, 100, 30);

        lbConc.setText("Concesionaria");
        getContentPane().add(lbConc);
        lbConc.setBounds(10, 50, 440, 290);

        jButtonCarros1.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCarros1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCarros1.setText("Carros ");
        jButtonCarros1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCarros1MouseClicked(evt);
            }
        });
        getContentPane().add(jButtonCarros1);
        jButtonCarros1.setBounds(160, 360, 130, 40);

        setSize(new java.awt.Dimension(472, 456));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseClicked
        JanelaAcesso.getJanelaAcesso().setVisible(true); this.dispose();
    }//GEN-LAST:event_btSairMouseClicked

    private void jButtonPneusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPneusMouseClicked
        JanelaPneuSQL.getJanelaPneu().setVisible(true);this.dispose();
    }//GEN-LAST:event_jButtonPneusMouseClicked

    private void jButtonAcessoriosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAcessoriosMouseClicked
        JanelaAcessorioSQL.getJanelaAcessorio().setVisible(true); this.dispose();
    }//GEN-LAST:event_jButtonAcessoriosMouseClicked

    private void jButtonCarros1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCarros1MouseClicked
        JanelaCarroSQL.getJanelaCarro().setVisible(true); this.dispose();
    }//GEN-LAST:event_jButtonCarros1MouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JButton jButtonAcessorios;
    private javax.swing.JButton jButtonCarros1;
    private javax.swing.JButton jButtonPneus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbConc;
    // End of variables declaration//GEN-END:variables
}
