/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.CarroDAO;
import javax.swing.table.DefaultTableModel;
import Model.Carro;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius Santiago
 */
public class JanelaCarroSQL extends javax.swing.JFrame {
    
    CarroDAO dao = CarroDAO.getCarroDao();
    private Carro instrumento = new Carro();
    private static JanelaCarroSQL janelaCarro;

    public static JanelaCarroSQL getJanelaCarro() {
        if (janelaCarro == null) {
            janelaCarro = new JanelaCarroSQL();
        }
        return janelaCarro;
    }
    
    /**
     * Creates new form JanelaCarro
     */
    private JanelaCarroSQL() {
        this.setTitle("Carros");
        initComponents();
        
        if (dao.CriaConexao()) {
            listarTab();
        }
    }
    
    public void listarTab(){
        DefaultTableModel modelo = (DefaultTableModel) tblInst.getModel();
        
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        try{
            dao.ConsultarTodos();
            dao.getRsdados();
            
            while(dao.getRsdados().next()){
                instrumento = dao.getCarro();
                modelo.insertRow(posLin, new Object[]{instrumento.getId(), instrumento.getNome(), instrumento.getChassi(), instrumento.getMarca()});
                posLin++;
            }
        } catch (SQLException erro) {
            System.out.println("Falha na conexao, comando sql = " + erro);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextChassi = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jButtonGravar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInst = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        Busca = new javax.swing.JButton();
        Deleta = new javax.swing.JButton();
        Edita = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 550));

        jLabel1.setText("Nome:");

        jLabel2.setText("Chassi");

        jLabel3.setText("Marca");

        jButtonGravar.setText("Gravar");
        jButtonGravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGravarMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel4.setText("CARROS");

        tblInst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Nº Chassi", "Marca"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInst);
        if (tblInst.getColumnModel().getColumnCount() > 0) {
            tblInst.getColumnModel().getColumn(0).setResizable(false);
            tblInst.getColumnModel().getColumn(1).setResizable(false);
            tblInst.getColumnModel().getColumn(2).setResizable(false);
            tblInst.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel5.setText("OPERAÇÕES COM ID:");

        Busca.setText("Buscar");
        Busca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscaMouseClicked(evt);
            }
        });

        Deleta.setText("Deletar");
        Deleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletaMouseClicked(evt);
            }
        });

        Edita.setText("Editar");
        Edita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditaMouseClicked(evt);
            }
        });

        jButton1.setText("Menu Inicial");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextChassi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldNome)
                                .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Edita, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Deleta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Busca, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(jLabel4)
                                    .addGap(145, 145, 145)
                                    .addComponent(jButton1)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jButtonGravar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Busca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Edita)
                        .addGap(38, 38, 38)
                        .addComponent(Deleta))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGravarMouseClicked
        int id = 0;
        
        try{
            dao.ConsultarTodos();
            dao.getRsdados();
            
            while(dao.getRsdados().next()){
                id++;
            }
        } catch (SQLException erro) {
            System.out.println("Falha na conexao, comando sql = " + erro);
        } 
        try {
            instrumento.setId(id);
            instrumento.setNome(jTextFieldNome.getText());
            instrumento.setChassi(Integer.valueOf(jTextChassi.getText()));
            instrumento.setMarca(jTextFieldMarca.getText());
            Carro car = instrumento;
            if (dao.Inserir(car)) {
                JOptionPane.showMessageDialog(this, "Carro inserido com sucesso."); listarTab();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao inserir Carro.");
            }    
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "O número de chassi deve ser em número", "Erro input de chassi", 0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!!!");
        }
    }//GEN-LAST:event_jButtonGravarMouseClicked

    private void DeletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletaMouseClicked
        int id = Integer.parseInt(jTextFieldId.getText());
        
        Carro deleted = new Carro();
        
        try{
            dao.ConsultarTodos();
            dao.getRsdados();
            
            while(dao.getRsdados().next()){
                instrumento = dao.getCarro();
                if(instrumento.getId() == id){
                    if (dao.Excluir(instrumento)) {
                        JOptionPane.showMessageDialog(this, "Carro excluído com sucesso."); listarTab();
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ao excluir carro.");
                    }
                }
            }
        } catch (SQLException erro) {
            System.out.println("Falha na conexao, comando sql = " + erro);
        }  
        listarTab(); 
    }//GEN-LAST:event_DeletaMouseClicked

    private void BuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscaMouseClicked
        int id = Integer.parseInt(jTextFieldId.getText());
        
        try{
            dao.ConsultarTodos();
            dao.getRsdados();
            
            while(dao.getRsdados().next()){
                instrumento = dao.getCarro();
                if(instrumento.getId() == id){
                    DefaultTableModel modelo = (DefaultTableModel) tblInst.getModel();
        
                    int posLin = 0;
                    modelo.setRowCount(posLin);
                
                    modelo.insertRow(posLin, new Object[]{instrumento.getId(), instrumento.getNome(), instrumento.getChassi(), instrumento.getMarca()});
                } 
            }
            jTextFieldNome.setText(instrumento.getNome());
            jTextChassi.setText(String.valueOf(instrumento.getChassi()));
            jTextFieldMarca.setText(instrumento.getMarca());
        } catch (SQLException erro) {
            System.out.println("Falha na conexao, comando sql = " + erro);
        }  
    }//GEN-LAST:event_BuscaMouseClicked

    private void EditaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditaMouseClicked
        try {
            int id = Integer.parseInt(jTextFieldId.getText());
            instrumento.setId(id);
            instrumento.setNome(jTextFieldNome.getText());
            instrumento.setChassi(Integer.valueOf(jTextChassi.getText()));
            instrumento.setMarca(jTextFieldMarca.getText());
            if (dao.Alterar(instrumento)) {
                JOptionPane.showMessageDialog(this, "Carro alterado com sucesso."); listarTab();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar carro.");
            }
            listarTab();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!!!");
        }
         
    }//GEN-LAST:event_EditaMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose(); JanelaInicial.getJanelaInicio().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Busca;
    private javax.swing.JButton Deleta;
    private javax.swing.JButton Edita;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextChassi;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTable tblInst;
    // End of variables declaration//GEN-END:variables
}
