/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.PneuDAO;
import javax.swing.table.DefaultTableModel;
import Model.Pneu;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius Santiago
 */
public class JanelaPneuSQL extends javax.swing.JFrame {
    
    PneuDAO dao = PneuDAO.getPneuDao();
    private Pneu instrumento = new Pneu();
    private static JanelaPneuSQL janelaPneu;

    public static JanelaPneuSQL getJanelaPneu() {
        if (janelaPneu == null) {
            janelaPneu = new JanelaPneuSQL();
        }
        return janelaPneu;
    }
    
    /**
     * Creates new form JanelaPneu
     */
    private JanelaPneuSQL() {
        this.setTitle("Pneus");
        initComponents();
        
        if (dao.CriaConexao()) {
            listarTab();
        }
    }
    
    public void listarTab(){
        DefaultTableModel modelo = (DefaultTableModel) tblInst.getModel();
        
        int posLin = 0;
        modelo.setRowCount(posLin);
        
        try{
            dao.ConsultarTodos();
            dao.getRsdados();
            
            while(dao.getRsdados().next()){
                instrumento = dao.getPneu();
                modelo.insertRow(posLin, new Object[]{instrumento.getId(), instrumento.getNome(), instrumento.getPreco(), instrumento.getDescricao()});
                posLin++;
            }
        } catch (SQLException erro) {
            System.out.println("Falha na conexao, comando sql = " + erro);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPreco = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        jButtonGravar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInst = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        Busca = new javax.swing.JButton();
        Deleta = new javax.swing.JButton();
        Edita = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 550));

        jLabel1.setText("Nome:");

        jLabel2.setText("Preco");

        jLabel3.setText("Descrição");

        jButtonGravar.setText("Gravar");
        jButtonGravar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGravarMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel4.setText("PNEU");

        tblInst.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Preço", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInst);
        if (tblInst.getColumnModel().getColumnCount() > 0) {
            tblInst.getColumnModel().getColumn(0).setMinWidth(5);
            tblInst.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel5.setText("OPERAÇÕES COM ID:");

        Busca.setText("Buscar");
        Busca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscaMouseClicked(evt);
            }
        });

        Deleta.setText("Deletar");
        Deleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletaMouseClicked(evt);
            }
        });

        Edita.setText("Editar");
        Edita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditaMouseClicked(evt);
            }
        });

        jButton1.setText("Menu Inicial");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNome)
                                    .addComponent(jTextFieldDescricao)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(136, 136, 136)
                                        .addComponent(jButton1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Busca, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Deleta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Edita, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(20, 20, 20))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jButton1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonGravar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Busca)
                    .addComponent(Deleta)
                    .addComponent(Edita))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(505, 421));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGravarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGravarMouseClicked
        int id = 0;
        
        try{
            dao.ConsultarTodos();
            dao.getRsdados();
            
            while(dao.getRsdados().next()){
                id++;
            }
        } catch (SQLException erro) {
            System.out.println("Falha na conexao, comando sql = " + erro);
        } 
        try {
            instrumento.setId(id);
            instrumento.setNome(jTextFieldNome.getText());
            instrumento.setPreco(Double.valueOf(jTextFieldPreco.getText()));
            instrumento.setDescricao(jTextFieldDescricao.getText());

            Pneu cli = instrumento;
            if (dao.Inserir(cli)) {
                JOptionPane.showMessageDialog(this, "Pneu inserido com sucesso."); listarTab();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao inserir pneu.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "O preço deve ser em número", "Erro input de preço", 0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!!!");
        }

    }//GEN-LAST:event_jButtonGravarMouseClicked

    private void DeletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletaMouseClicked
        int id = Integer.parseInt(jTextFieldId.getText());
        
        Pneu deleted = new Pneu();
        
        try{
            dao.ConsultarTodos();
            dao.getRsdados();
            
            while(dao.getRsdados().next()){
                instrumento = dao.getPneu();
                if(instrumento.getId() == id){
                    if (dao.Excluir(instrumento)) {
                        JOptionPane.showMessageDialog(this, "Pneu excluído com sucesso."); listarTab();
                    } else {
                        JOptionPane.showMessageDialog(this, "Erro ao excluir Pneu.");
                    }
                }
            }
        } catch (SQLException erro) {
            System.out.println("Falha na conexao, comando sql = " + erro);
        }  
        listarTab(); 
    }//GEN-LAST:event_DeletaMouseClicked

    private void BuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscaMouseClicked
        int id = Integer.parseInt(jTextFieldId.getText());
        
        try{
            dao.ConsultarTodos();
            dao.getRsdados();
            
            while(dao.getRsdados().next()){
                instrumento = dao.getPneu();
                if(instrumento.getId() == id){
                    DefaultTableModel modelo = (DefaultTableModel) tblInst.getModel();
        
                    int posLin = 0;
                    modelo.setRowCount(posLin);
                
                    modelo.insertRow(posLin, new Object[]{instrumento.getId(), instrumento.getNome(), instrumento.getPreco(), instrumento.getDescricao()});
                } break;
            }
            jTextFieldNome.setText(instrumento.getNome());
            jTextFieldPreco.setText(String.valueOf(instrumento.getPreco()));
            jTextFieldDescricao.setText(instrumento.getDescricao());
        } catch (SQLException erro) {
            System.out.println("Falha na conexao, comando sql = " + erro);
        }  
    }//GEN-LAST:event_BuscaMouseClicked

    private void EditaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditaMouseClicked
        try {
            int id = Integer.parseInt(jTextFieldId.getText());
            instrumento.setId(id);
            instrumento.setNome(jTextFieldNome.getText());
            instrumento.setPreco(Double.valueOf(jTextFieldPreco.getText()));
            instrumento.setDescricao(jTextFieldDescricao.getText());
            if (dao.Alterar(instrumento)) {
                JOptionPane.showMessageDialog(this, "Pneu alterado com sucesso."); listarTab();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar Pneu.");
            }
            listarTab();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!!!");
        }
         
    }//GEN-LAST:event_EditaMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose(); JanelaInicial.getJanelaInicio().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Busca;
    private javax.swing.JButton Deleta;
    private javax.swing.JButton Edita;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTable tblInst;
    // End of variables declaration//GEN-END:variables
}
